package mcp_test

import (
	"encoding/json"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"nexus-orchestrator/internal/adapters/inbound/mcp"
	"nexus-orchestrator/internal/adapters/outbound/fs_writer"
	"nexus-orchestrator/internal/adapters/outbound/repo_sqlite"
	"nexus-orchestrator/internal/core/domain"
	"nexus-orchestrator/internal/core/services"
)

// --- Mock LLM that implements ports.LLMClient ---

type integrationMockLLM struct{}

func (m *integrationMockLLM) Ping() bool           { return true }
func (m *integrationMockLLM) ProviderName() string { return "MockLLM" }
func (m *integrationMockLLM) ActiveModel() string  { return "mock-model" }
func (m *integrationMockLLM) BaseURL() string      { return "" }
func (m *integrationMockLLM) GetAvailableModels() ([]string, error) {
	return []string{"mock-model"}, nil
}
func (m *integrationMockLLM) ContextLimit() int { return 0 }
func (m *integrationMockLLM) GenerateCode(_ string) (string, error) {
	return "// generated by MockLLM\npackage main", nil
}
func (m *integrationMockLLM) Chat(_ []domain.Message) (string, error) {
	return "// generated by MockLLM\npackage main", nil
}

// --- Test stack ---

type mcpTestStack struct {
	srv    *httptest.Server
	orch   *services.OrchestratorService
	repo   *repo_sqlite.Repository
	tmpDir string
}

func newMCPTestStack(t *testing.T) *mcpTestStack {
	t.Helper()

	dbFile, err := os.CreateTemp(t.TempDir(), "nexus-mcp-test-*.db")
	if err != nil {
		t.Fatalf("create temp db: %v", err)
	}
	dbPath := dbFile.Name()
	dbFile.Close()

	repo, err := repo_sqlite.New(dbPath)
	if err != nil {
		t.Fatalf("open repo: %v", err)
	}

	sessionRepo := repo_sqlite.NewSessionRepo(repo)
	writer := fs_writer.New()
	discovery := services.NewDiscoveryService(&integrationMockLLM{})
	orch := services.NewOrchestrator(discovery, repo, writer, sessionRepo)

	mcpSrv := mcp.NewServer(orch)
	srv := httptest.NewServer(mcpSrv)

	t.Cleanup(func() {
		srv.Close()
		orch.Stop()
		_ = repo.Close()
	})

	return &mcpTestStack{
		srv:    srv,
		orch:   orch,
		repo:   repo,
		tmpDir: t.TempDir(),
	}
}

// --- JSON-RPC helpers (rpcResp / postRPC are in server_test.go) ---

func callTool(t *testing.T, srv *httptest.Server, id int, tool string, args map[string]any) rpcResp {
	t.Helper()
	return postRPC(t, srv, map[string]any{
		"jsonrpc": "2.0",
		"id":      id,
		"method":  "tools/call",
		"params": map[string]any{
			"name":      tool,
			"arguments": args,
		},
	})
}

// extractToolText unmarshals the first content[].text from a tools/call result.
func extractToolText(t *testing.T, r rpcResp) string {
	t.Helper()
	if r.Error != nil {
		t.Fatalf("unexpected RPC error: code=%d msg=%s", r.Error.Code, r.Error.Message)
	}
	var result struct {
		Content []struct {
			Text string `json:"text"`
		} `json:"content"`
	}
	if err := json.Unmarshal(r.Result, &result); err != nil {
		t.Fatalf("unmarshal result: %v", err)
	}
	if len(result.Content) == 0 {
		t.Fatal("expected content in result")
	}
	return result.Content[0].Text
}

// --- Integration tests ---

func TestMCPIntegration_SubmitAndComplete(t *testing.T) {
	ts := newMCPTestStack(t)

	// Submit a task via MCP
	r := callTool(t, ts.srv, 1, "submit_task", map[string]any{
		"projectPath": ts.tmpDir,
		"targetFile":  "out.go",
		"instruction": "generate foo",
	})
	text := extractToolText(t, r)

	var submitPayload map[string]string
	if err := json.Unmarshal([]byte(text), &submitPayload); err != nil {
		t.Fatalf("unmarshal submit result: %v", err)
	}
	taskID := submitPayload["id"]
	if taskID == "" {
		t.Fatal("expected non-empty task id")
	}

	// Poll get_task until COMPLETED (timeout 15s)
	deadline := time.Now().Add(15 * time.Second)
	var finalStatus string
	for time.Now().Before(deadline) {
		time.Sleep(200 * time.Millisecond)

		r := callTool(t, ts.srv, 2, "get_task", map[string]any{"id": taskID})
		text := extractToolText(t, r)

		var task domain.Task
		if err := json.Unmarshal([]byte(text), &task); err != nil {
			t.Fatalf("unmarshal task: %v", err)
		}
		finalStatus = string(task.Status)
		if task.Status == domain.StatusCompleted || task.Status == domain.StatusFailed {
			break
		}
	}
	if finalStatus != string(domain.StatusCompleted) {
		t.Fatalf("expected COMPLETED, got %s", finalStatus)
	}

	// Verify queue is empty (or only contains completed tasks)
	r = callTool(t, ts.srv, 3, "get_queue", map[string]any{})
	queueText := extractToolText(t, r)
	var queue []domain.Task
	if err := json.Unmarshal([]byte(queueText), &queue); err != nil {
		t.Fatalf("unmarshal queue: %v", err)
	}
	for _, q := range queue {
		if q.ID == taskID && q.Status == domain.StatusQueued {
			t.Error("task should no longer be QUEUED in the queue")
		}
	}

	// Verify output file exists and contains MockLLM marker
	outPath := filepath.Join(ts.tmpDir, "out.go")
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("output file not written: %v", err)
	}
	if !strings.Contains(string(content), "MockLLM") {
		t.Errorf("output file does not contain MockLLM marker: %s", string(content))
	}
}

func TestMCPIntegration_CancelTask(t *testing.T) {
	ts := newMCPTestStack(t)

	// Submit a task
	r := callTool(t, ts.srv, 1, "submit_task", map[string]any{
		"projectPath": ts.tmpDir,
		"targetFile":  "cancel.go",
		"instruction": "generate bar",
	})
	text := extractToolText(t, r)

	var submitPayload map[string]string
	if err := json.Unmarshal([]byte(text), &submitPayload); err != nil {
		t.Fatalf("unmarshal submit result: %v", err)
	}
	taskID := submitPayload["id"]

	// Brief sleep then attempt cancel — there's a race between the worker
	// completing the task and our cancel call, so we accept either outcome.
	time.Sleep(50 * time.Millisecond)
	cancelR := callTool(t, ts.srv, 2, "cancel_task", map[string]any{"id": taskID})

	// Poll get_task to determine final status
	deadline := time.Now().Add(10 * time.Second)
	var finalStatus domain.TaskStatus
	for time.Now().Before(deadline) {
		time.Sleep(200 * time.Millisecond)

		r := callTool(t, ts.srv, 3, "get_task", map[string]any{"id": taskID})
		text := extractToolText(t, r)

		var task domain.Task
		if err := json.Unmarshal([]byte(text), &task); err != nil {
			t.Fatalf("unmarshal task: %v", err)
		}
		finalStatus = task.Status
		if finalStatus == domain.StatusCancelled || finalStatus == domain.StatusCompleted {
			break
		}
	}

	// Accept either CANCELLED or COMPLETED — the race is inherent
	if finalStatus != domain.StatusCancelled && finalStatus != domain.StatusCompleted {
		t.Errorf("expected CANCELLED or COMPLETED, got %s", finalStatus)
	}

	// If cancel succeeded, verify the RPC response was successful
	if finalStatus == domain.StatusCancelled && cancelR.Error != nil {
		t.Errorf("cancel_task returned error: %s", cancelR.Error.Message)
	}
}

func TestMCPIntegration_GetProviders(t *testing.T) {
	ts := newMCPTestStack(t)

	r := callTool(t, ts.srv, 1, "get_providers", map[string]any{})
	text := extractToolText(t, r)

	var providers []struct {
		Name   string `json:"name"`
		Active bool   `json:"active"`
	}
	if err := json.Unmarshal([]byte(text), &providers); err != nil {
		t.Fatalf("unmarshal providers: %v", err)
	}

	found := false
	for _, p := range providers {
		if p.Name == "MockLLM" && p.Active {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("expected provider MockLLM with active=true, got: %s", text)
	}
}

func TestMCPIntegration_HealthTool(t *testing.T) {
	ts := newMCPTestStack(t)

	r := callTool(t, ts.srv, 1, "health", map[string]any{})
	text := extractToolText(t, r)

	if !strings.Contains(text, "ok") {
		t.Errorf("expected health result to contain 'ok', got: %s", text)
	}
}
