package services_test

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
	"time"

	"nexus-orchestrator/internal/adapters/inbound/httpapi"
	"nexus-orchestrator/internal/adapters/outbound/fs_writer"
	"nexus-orchestrator/internal/adapters/outbound/repo_sqlite"
	"nexus-orchestrator/internal/core/domain"
	"nexus-orchestrator/internal/core/services"
)

// mockLLM is a test double that always responds with a known code snippet.
type mockLLM struct{}

func (m *mockLLM) Ping() bool                              { return true }
func (m *mockLLM) ProviderName() string                    { return "MockLLM" }
func (m *mockLLM) ActiveModel() string                     { return "mock-model" }
func (m *mockLLM) GetAvailableModels() ([]string, error)   { return []string{"mock-model"}, nil }
func (m *mockLLM) ContextLimit() int                       { return 0 }
func (m *mockLLM) GenerateCode(_ string) (string, error)   { return "// generated by MockLLM\npackage main", nil }
func (m *mockLLM) Chat(_ []domain.Message) (string, error) { return "// generated by MockLLM\npackage main", nil }

// testStack wires the full in-process stack and returns useful handles.
type testStack struct {
	orch    *services.OrchestratorService
	server  *httpapi.Server
	repo    *repo_sqlite.Repository
	hub     *httpapi.Hub
	tmpDir  string
	dbPath  string
	cleanup func()
}

func newTestStack(t *testing.T) *testStack {
	t.Helper()

	// Temp DB
	dbFile, err := os.CreateTemp(t.TempDir(), "nexus-test-*.db")
	if err != nil {
		t.Fatalf("create temp db: %v", err)
	}
	dbPath := dbFile.Name()
	dbFile.Close()

	repo, err := repo_sqlite.New(dbPath)
	if err != nil {
		t.Fatalf("open repo: %v", err)
	}

	sessionRepo := repo_sqlite.NewSessionRepo(repo)
	tmpDir := t.TempDir()
	writer := fs_writer.New()
	discovery := services.NewDiscoveryService(&mockLLM{})
	orch := services.NewOrchestrator(discovery, repo, writer, sessionRepo)

	hub := httpapi.NewHub()
	orch.SetBroadcaster(hub)
	server := httpapi.NewServer(orch, hub)

	return &testStack{
		orch:   orch,
		server: server,
		repo:   repo,
		hub:    hub,
		tmpDir: tmpDir,
		dbPath: dbPath,
		cleanup: func() {
			orch.Stop()
			_ = repo.Close()
		},
	}
}

// TestFullPipelineHTTP submits a task through the HTTP API and polls until it completes.
func TestFullPipelineHTTP(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	body := map[string]interface{}{
		"projectPath":  ts.tmpDir,
		"targetFile":   "out.go",
		"instruction":  "generate a foo function",
		"contextFiles": []string{},
	}
	reqJSON, err := json.Marshal(body)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	resp, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(reqJSON))
	if err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("expected 201, got %d", resp.StatusCode)
	}

	var created struct {
		TaskID string `json:"task_id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	if created.TaskID == "" {
		t.Fatal("expected non-empty task_id")
	}

	// Poll until status == COMPLETED (timeout 15 s)
	deadline := time.Now().Add(15 * time.Second)
	var finalStatus domain.TaskStatus
	for time.Now().Before(deadline) {
		time.Sleep(250 * time.Millisecond)

		r, err := http.Get(srv.URL + "/api/tasks/" + created.TaskID)
		if err != nil {
			continue
		}
		var task domain.Task
		if err := json.NewDecoder(r.Body).Decode(&task); err != nil {
			r.Body.Close()
			continue
		}
		r.Body.Close()
		finalStatus = task.Status
		if finalStatus == domain.StatusCompleted || finalStatus == domain.StatusFailed {
			break
		}
	}

	if finalStatus != domain.StatusCompleted {
		t.Errorf("expected status COMPLETED, got %s", finalStatus)
	}

	// Verify output file was written
	outPath := ts.tmpDir + "/out.go"
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("output file not written: %v", err)
	}
	if !bytes.Contains(content, []byte("MockLLM")) {
		t.Errorf("expected output to contain 'MockLLM', got: %s", content)
	}
}

// TestDashboardReturns200 verifies GET /ui returns a valid HTML response.
func TestDashboardReturns200(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/ui")
	if err != nil {
		t.Fatalf("GET /ui: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200, got %d", resp.StatusCode)
	}
	ct := resp.Header.Get("Content-Type")
	if ct == "" {
		t.Error("expected Content-Type header")
	}
	if len(ct) < 9 || ct[:9] != "text/html" {
		t.Errorf("expected text/html Content-Type, got %s", ct)
	}
}

// TestRootRedirectsToUI verifies GET / redirects to /ui.
func TestRootRedirectsToUI(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	client := &http.Client{
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := client.Get(srv.URL + "/")
	if err != nil {
		t.Fatalf("GET /: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusFound {
		t.Errorf("expected 302, got %d", resp.StatusCode)
	}
	if loc := resp.Header.Get("Location"); loc != "/ui" {
		t.Errorf("expected Location: /ui, got %s", loc)
	}
}

// TestSSEEndpointResponds verifies GET /api/events returns a 200 with text/event-stream.
// The connection stays open (SSE is long-lived), so a 2 s client timeout is used.
func TestSSEEndpointResponds(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(srv.URL + "/api/events")
	if err != nil {
		// A timeout means the server IS serving SSE (connection stayed open) — that's fine.
		t.Logf("SSE response (timeout expected for long-lived connection): %v", err)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200 for SSE endpoint, got %d", resp.StatusCode)
	}
}

// TestHealthEndpoint verifies GET /api/health returns {status: "ok"}.
func TestHealthEndpoint(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/api/health")
	if err != nil {
		t.Fatalf("GET /api/health: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200, got %d", resp.StatusCode)
	}
	var health map[string]string
	if err := json.NewDecoder(resp.Body).Decode(&health); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if health["status"] != "ok" {
		t.Errorf("expected status=ok, got %v", health)
	}
}
