package services_test

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"nexus-orchestrator/internal/adapters/inbound/httpapi"
	"nexus-orchestrator/internal/adapters/outbound/fs_writer"
	"nexus-orchestrator/internal/adapters/outbound/repo_sqlite"
	"nexus-orchestrator/internal/core/domain"
	"nexus-orchestrator/internal/core/ports"
	"nexus-orchestrator/internal/core/services"
)

// mockLLM is a test double that always responds with a known code snippet.
type mockLLM struct{}

func (m *mockLLM) Ping() bool                            { return true }
func (m *mockLLM) ProviderName() string                  { return "MockLLM" }
func (m *mockLLM) ActiveModel() string                   { return "mock-model" }
func (m *mockLLM) GetAvailableModels() ([]string, error) { return []string{"mock-model"}, nil }
func (m *mockLLM) ContextLimit() int                     { return 0 }
func (m *mockLLM) GenerateCode(_ string) (string, error) {
	return "// generated by MockLLM\npackage main", nil
}
func (m *mockLLM) Chat(_ []domain.Message) (string, error) {
	return "// generated by MockLLM\npackage main", nil
}

// blockingMockLLM blocks in GenerateCode/Chat until releaseCh is closed.
// Used by TestCancelTaskHTTP to keep the worker busy so queued tasks can be cancelled.
type blockingMockLLM struct {
	releaseCh chan struct{}
}

func (m *blockingMockLLM) Ping() bool                            { return true }
func (m *blockingMockLLM) ProviderName() string                  { return "MockLLM" }
func (m *blockingMockLLM) ActiveModel() string                   { return "mock-model" }
func (m *blockingMockLLM) GetAvailableModels() ([]string, error) { return []string{"mock-model"}, nil }
func (m *blockingMockLLM) ContextLimit() int                     { return 0 }
func (m *blockingMockLLM) GenerateCode(_ string) (string, error) {
	<-m.releaseCh
	return "// generated by MockLLM\npackage main", nil
}
func (m *blockingMockLLM) Chat(_ []domain.Message) (string, error) {
	<-m.releaseCh
	return "// generated by MockLLM\npackage main", nil
}

// testStack wires the full in-process stack and returns useful handles.
type testStack struct {
	orch    *services.OrchestratorService
	server  *httpapi.Server
	repo    *repo_sqlite.Repository
	hub     *httpapi.Hub
	tmpDir  string
	dbPath  string
	cleanup func()
}

func newTestStack(t *testing.T) *testStack {
	t.Helper()

	// Temp DB
	dbFile, err := os.CreateTemp(t.TempDir(), "nexus-test-*.db")
	if err != nil {
		t.Fatalf("create temp db: %v", err)
	}
	dbPath := dbFile.Name()
	dbFile.Close()

	repo, err := repo_sqlite.New(dbPath)
	if err != nil {
		t.Fatalf("open repo: %v", err)
	}

	sessionRepo := repo_sqlite.NewSessionRepo(repo)
	tmpDir := t.TempDir()
	writer := fs_writer.New()
	discovery := services.NewDiscoveryService(&mockLLM{})
	orch := services.NewOrchestrator(discovery, repo, writer, sessionRepo)

	hub := httpapi.NewHub()
	orch.SetBroadcaster(hub)
	server := httpapi.NewServer(orch, hub)

	return &testStack{
		orch:   orch,
		server: server,
		repo:   repo,
		hub:    hub,
		tmpDir: tmpDir,
		dbPath: dbPath,
		cleanup: func() {
			orch.Stop()
			_ = repo.Close()
		},
	}
}

// newTestStackWithLLM is like newTestStack but accepts a custom LLM client.
func newTestStackWithLLM(t *testing.T, llm ports.LLMClient) *testStack {
	t.Helper()

	dbFile, err := os.CreateTemp(t.TempDir(), "nexus-test-*.db")
	if err != nil {
		t.Fatalf("create temp db: %v", err)
	}
	dbPath := dbFile.Name()
	dbFile.Close()

	repo, err := repo_sqlite.New(dbPath)
	if err != nil {
		t.Fatalf("open repo: %v", err)
	}

	sessionRepo := repo_sqlite.NewSessionRepo(repo)
	tmpDir := t.TempDir()
	writer := fs_writer.New()
	discovery := services.NewDiscoveryService(llm)
	orch := services.NewOrchestrator(discovery, repo, writer, sessionRepo)

	hub := httpapi.NewHub()
	orch.SetBroadcaster(hub)
	server := httpapi.NewServer(orch, hub)

	return &testStack{
		orch:   orch,
		server: server,
		repo:   repo,
		hub:    hub,
		tmpDir: tmpDir,
		dbPath: dbPath,
		cleanup: func() {
			orch.Stop()
			_ = repo.Close()
		},
	}
}

// TestFullPipelineHTTP submits a task through the HTTP API and polls until it completes.
func TestFullPipelineHTTP(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	body := map[string]interface{}{
		"projectPath":  ts.tmpDir,
		"targetFile":   "out.go",
		"instruction":  "generate a foo function",
		"contextFiles": []string{},
	}
	reqJSON, err := json.Marshal(body)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	resp, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(reqJSON))
	if err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("expected 201, got %d", resp.StatusCode)
	}

	var created struct {
		TaskID string `json:"task_id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	if created.TaskID == "" {
		t.Fatal("expected non-empty task_id")
	}

	// Poll until status == COMPLETED (timeout 15 s)
	deadline := time.Now().Add(15 * time.Second)
	var finalStatus domain.TaskStatus
	for time.Now().Before(deadline) {
		time.Sleep(250 * time.Millisecond)

		r, err := http.Get(srv.URL + "/api/tasks/" + created.TaskID)
		if err != nil {
			continue
		}
		var task domain.Task
		if err := json.NewDecoder(r.Body).Decode(&task); err != nil {
			r.Body.Close()
			continue
		}
		r.Body.Close()
		finalStatus = task.Status
		if finalStatus == domain.StatusCompleted || finalStatus == domain.StatusFailed {
			break
		}
	}

	if finalStatus != domain.StatusCompleted {
		t.Errorf("expected status COMPLETED, got %s", finalStatus)
	}

	// Verify output file was written
	outPath := ts.tmpDir + "/out.go"
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("output file not written: %v", err)
	}
	if !bytes.Contains(content, []byte("MockLLM")) {
		t.Errorf("expected output to contain 'MockLLM', got: %s", content)
	}
}

// TestDashboardReturns200 verifies GET /ui returns a valid HTML response.
func TestDashboardReturns200(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/ui")
	if err != nil {
		t.Fatalf("GET /ui: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200, got %d", resp.StatusCode)
	}
	ct := resp.Header.Get("Content-Type")
	if ct == "" {
		t.Error("expected Content-Type header")
	}
	if len(ct) < 9 || ct[:9] != "text/html" {
		t.Errorf("expected text/html Content-Type, got %s", ct)
	}
}

// TestRootRedirectsToUI verifies GET / redirects to /ui.
func TestRootRedirectsToUI(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	client := &http.Client{
		CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := client.Get(srv.URL + "/")
	if err != nil {
		t.Fatalf("GET /: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusFound {
		t.Errorf("expected 302, got %d", resp.StatusCode)
	}
	if loc := resp.Header.Get("Location"); loc != "/ui" {
		t.Errorf("expected Location: /ui, got %s", loc)
	}
}

// TestSSEEndpointResponds verifies GET /api/events returns a 200 with text/event-stream.
// The connection stays open (SSE is long-lived), so a 2 s client timeout is used.
func TestSSEEndpointResponds(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(srv.URL + "/api/events")
	if err != nil {
		// A timeout means the server IS serving SSE (connection stayed open) — that's fine.
		t.Logf("SSE response (timeout expected for long-lived connection): %v", err)
		return
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200 for SSE endpoint, got %d", resp.StatusCode)
	}
}

// TestSSEEventLifecycle submits a task and verifies the correct SSE events
// are received in order: task.queued → task.processing → task.completed.
func TestSSEEventLifecycle(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	type sseEvent struct {
		Type   string `json:"type"`
		TaskID string `json:"taskId"`
	}

	events := make(chan sseEvent, 32)
	sseCtx, sseCancel := context.WithCancel(context.Background())
	defer sseCancel()

	// Start SSE reader goroutine
	go func() {
		req, err := http.NewRequestWithContext(sseCtx, http.MethodGet, srv.URL+"/api/events", nil)
		if err != nil {
			return
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return
		}
		defer resp.Body.Close()

		scanner := bufio.NewScanner(resp.Body)
		for scanner.Scan() {
			line := scanner.Text()
			if !strings.HasPrefix(line, "data: ") {
				continue
			}
			payload := strings.TrimPrefix(line, "data: ")
			var ev sseEvent
			if err := json.Unmarshal([]byte(payload), &ev); err != nil {
				continue
			}
			select {
			case events <- ev:
			case <-sseCtx.Done():
				return
			}
		}
	}()

	// Wait for the initial "connected" event
	select {
	case ev := <-events:
		if ev.Type != "connected" {
			t.Fatalf("expected first SSE event type 'connected', got %q", ev.Type)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("timed out waiting for SSE connected event")
	}

	// Submit a task via HTTP
	body := map[string]interface{}{
		"projectPath":  ts.tmpDir,
		"targetFile":   "sse_out.go",
		"instruction":  "generate a bar function",
		"contextFiles": []string{},
	}
	reqJSON, err := json.Marshal(body)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	resp, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(reqJSON))
	if err != nil {
		t.Fatalf("POST /api/tasks: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusCreated {
		t.Fatalf("expected 201, got %d", resp.StatusCode)
	}
	var created struct {
		TaskID string `json:"task_id"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
		t.Fatalf("decode create response: %v", err)
	}
	if created.TaskID == "" {
		t.Fatal("expected non-empty task_id")
	}

	// Collect events matching the submitted task for up to 15s
	wanted := []string{"task.queued", "task.processing", "task.completed"}
	var collected []string
	timeout := time.After(15 * time.Second)
collect:
	for {
		select {
		case ev := <-events:
			if ev.TaskID == created.TaskID {
				collected = append(collected, ev.Type)
			}
			if len(collected) >= len(wanted) {
				break collect
			}
		case <-timeout:
			break collect
		}
	}

	sseCancel()

	// Verify order: task.queued → task.processing → task.completed
	if len(collected) != len(wanted) {
		t.Fatalf("expected %d events %v, got %d: %v", len(wanted), wanted, len(collected), collected)
	}
	for i, w := range wanted {
		if collected[i] != w {
			t.Errorf("event[%d]: expected %q, got %q", i, w, collected[i])
		}
	}
}

// TestHealthEndpoint verifies GET /api/health returns {status: "ok"}.
func TestHealthEndpoint(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/api/health")
	if err != nil {
		t.Fatalf("GET /api/health: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Errorf("expected 200, got %d", resp.StatusCode)
	}
	var health map[string]string
	if err := json.NewDecoder(resp.Body).Decode(&health); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if health["status"] != "ok" {
		t.Errorf("expected status=ok, got %v", health)
	}
}

// TestCancelTaskHTTP submits two tasks through the HTTP API with a blocking LLM,
// cancels the second (still queued) task, and verifies it is marked CANCELLED.
func TestCancelTaskHTTP(t *testing.T) {
	release := make(chan struct{})

	ts := newTestStackWithLLM(t, &blockingMockLLM{releaseCh: release})
	// close(release) must run before ts.cleanup() so the blocking worker goroutine
	// is unblocked and can finish its current task before Stop() waits for it and
	// the database is closed. Defers run LIFO, so register cleanup first (runs last)
	// and release second (runs first).
	defer ts.cleanup()
	defer close(release)

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	// Submit task1 — the worker picks it up and blocks in the LLM call.
	task1JSON, _ := json.Marshal(map[string]interface{}{
		"projectPath":  ts.tmpDir,
		"targetFile":   "block.go",
		"instruction":  "blocking task",
		"contextFiles": []string{},
	})
	resp1, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(task1JSON))
	if err != nil {
		t.Fatalf("POST task1: %v", err)
	}
	resp1.Body.Close()
	if resp1.StatusCode != http.StatusCreated {
		t.Fatalf("task1: expected 201, got %d", resp1.StatusCode)
	}

	// Give the worker time to dequeue task1 and block on the LLM.
	time.Sleep(100 * time.Millisecond)

	// Submit task2 — it enters the queue while the worker is busy.
	task2JSON, _ := json.Marshal(map[string]interface{}{
		"projectPath":  ts.tmpDir,
		"targetFile":   "cancel_me.go",
		"instruction":  "task to cancel",
		"contextFiles": []string{},
	})
	resp2, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(task2JSON))
	if err != nil {
		t.Fatalf("POST task2: %v", err)
	}
	var created struct {
		TaskID string `json:"task_id"`
	}
	if err := json.NewDecoder(resp2.Body).Decode(&created); err != nil {
		t.Fatalf("decode task2 response: %v", err)
	}
	resp2.Body.Close()

	// Cancel task2 via DELETE.
	req, err := http.NewRequest(http.MethodDelete, srv.URL+"/api/tasks/"+created.TaskID, nil)
	if err != nil {
		t.Fatalf("build DELETE request: %v", err)
	}
	cancelResp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("DELETE /api/tasks/%s: %v", created.TaskID, err)
	}
	cancelResp.Body.Close()
	if cancelResp.StatusCode != http.StatusNoContent {
		t.Fatalf("cancel: expected 204, got %d", cancelResp.StatusCode)
	}

	// Verify the task status is CANCELLED.
	getResp, err := http.Get(srv.URL + "/api/tasks/" + created.TaskID)
	if err != nil {
		t.Fatalf("GET task: %v", err)
	}
	defer getResp.Body.Close()
	var task domain.Task
	if err := json.NewDecoder(getResp.Body).Decode(&task); err != nil {
		t.Fatalf("decode task: %v", err)
	}
	if task.Status != domain.StatusCancelled {
		t.Errorf("expected status CANCELLED, got %s", task.Status)
	}
}

// TestProviderLifecycleHTTP verifies the provider GET endpoints return the mock provider.
func TestProviderLifecycleHTTP(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	// GET /api/providers — should list MockLLM.
	resp, err := http.Get(srv.URL + "/api/providers")
	if err != nil {
		t.Fatalf("GET /api/providers: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("expected 200, got %d", resp.StatusCode)
	}

	var providers []struct {
		Name        string   `json:"name"`
		Active      bool     `json:"active"`
		ActiveModel string   `json:"activeModel"`
		Models      []string `json:"models"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&providers); err != nil {
		t.Fatalf("decode providers: %v", err)
	}

	found := false
	for _, p := range providers {
		if p.Name == "MockLLM" {
			found = true
			if !p.Active {
				t.Error("expected MockLLM active=true")
			}
			hasModel := false
			for _, m := range p.Models {
				if m == "mock-model" {
					hasModel = true
				}
			}
			if !hasModel {
				t.Errorf("expected MockLLM to have mock-model, got %v", p.Models)
			}
		}
	}
	if !found {
		t.Errorf("MockLLM not found in providers: %+v", providers)
	}

	// GET /api/providers/MockLLM/models — should return ["mock-model"].
	modelsResp, err := http.Get(srv.URL + "/api/providers/MockLLM/models")
	if err != nil {
		t.Fatalf("GET /api/providers/MockLLM/models: %v", err)
	}
	defer modelsResp.Body.Close()
	if modelsResp.StatusCode != http.StatusOK {
		t.Fatalf("models: expected 200, got %d", modelsResp.StatusCode)
	}

	var models []string
	if err := json.NewDecoder(modelsResp.Body).Decode(&models); err != nil {
		t.Fatalf("decode models: %v", err)
	}
	if len(models) != 1 || models[0] != "mock-model" {
		t.Errorf("expected [mock-model], got %v", models)
	}
}

// TestHTTPErrorScenarios is a table-driven test for various error responses.
func TestHTTPErrorScenarios(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	cases := []struct {
		name       string
		method     string
		path       string
		body       string
		wantStatus int
	}{
		{
			name:       "POST invalid JSON",
			method:     http.MethodPost,
			path:       "/api/tasks",
			body:       `{invalid`,
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "POST empty body",
			method:     http.MethodPost,
			path:       "/api/tasks",
			body:       "",
			wantStatus: http.StatusBadRequest,
		},
		{
			name:       "GET nonexistent task",
			method:     http.MethodGet,
			path:       "/api/tasks/00000000-0000-0000-0000-000000000000",
			body:       "",
			wantStatus: http.StatusNotFound,
		},
		{
			name:       "DELETE nonexistent task",
			method:     http.MethodDelete,
			path:       "/api/tasks/00000000-0000-0000-0000-000000000000",
			body:       "",
			wantStatus: http.StatusNotFound,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			var bodyReader *bytes.Reader
			if tc.body != "" {
				bodyReader = bytes.NewReader([]byte(tc.body))
			}

			var req *http.Request
			var err error
			if bodyReader != nil {
				req, err = http.NewRequest(tc.method, srv.URL+tc.path, bodyReader)
			} else {
				req, err = http.NewRequest(tc.method, srv.URL+tc.path, nil)
			}
			if err != nil {
				t.Fatalf("build request: %v", err)
			}
			if tc.method == http.MethodPost {
				req.Header.Set("Content-Type", "application/json")
			}

			resp, err := http.DefaultClient.Do(req)
			if err != nil {
				t.Fatalf("%s %s: %v", tc.method, tc.path, err)
			}
			resp.Body.Close()

			if resp.StatusCode != tc.wantStatus {
				t.Errorf("expected %d, got %d", tc.wantStatus, resp.StatusCode)
			}
		})
	}
}

// TestMultipleTasksCompleteHTTP submits 3 tasks and verifies all complete with output files.
func TestMultipleTasksCompleteHTTP(t *testing.T) {
	ts := newTestStack(t)
	defer ts.cleanup()

	srv := httptest.NewServer(ts.server.Handler())
	defer srv.Close()

	targets := []string{"a.go", "b.go", "c.go"}
	taskIDs := make([]string, 0, len(targets))

	for _, target := range targets {
		body, _ := json.Marshal(map[string]interface{}{
			"projectPath":  ts.tmpDir,
			"targetFile":   target,
			"instruction":  "generate code for " + target,
			"contextFiles": []string{},
		})
		resp, err := http.Post(srv.URL+"/api/tasks", "application/json", bytes.NewReader(body))
		if err != nil {
			t.Fatalf("POST task %s: %v", target, err)
		}
		if resp.StatusCode != http.StatusCreated {
			resp.Body.Close()
			t.Fatalf("task %s: expected 201, got %d", target, resp.StatusCode)
		}
		var created struct {
			TaskID string `json:"task_id"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&created); err != nil {
			resp.Body.Close()
			t.Fatalf("decode task %s: %v", target, err)
		}
		resp.Body.Close()
		taskIDs = append(taskIDs, created.TaskID)
	}

	// Poll all tasks until COMPLETED (timeout 20s).
	deadline := time.Now().Add(20 * time.Second)
	for _, id := range taskIDs {
		for time.Now().Before(deadline) {
			r, err := http.Get(srv.URL + "/api/tasks/" + id)
			if err != nil {
				time.Sleep(250 * time.Millisecond)
				continue
			}
			var task domain.Task
			if err := json.NewDecoder(r.Body).Decode(&task); err != nil {
				r.Body.Close()
				time.Sleep(250 * time.Millisecond)
				continue
			}
			r.Body.Close()
			if task.Status == domain.StatusCompleted {
				break
			}
			if task.Status == domain.StatusFailed {
				t.Fatalf("task %s failed: %s", id, task.Logs)
			}
			time.Sleep(250 * time.Millisecond)
		}
	}

	// Verify output files exist.
	for _, target := range targets {
		path := ts.tmpDir + "/" + target
		content, err := os.ReadFile(path)
		if err != nil {
			t.Errorf("output file %s not written: %v", target, err)
			continue
		}
		if !bytes.Contains(content, []byte("MockLLM")) {
			t.Errorf("file %s: expected 'MockLLM' in content, got: %s", target, content)
		}
	}

	// Verify all 3 tasks are individually retrievable and COMPLETED.
	for i, id := range taskIDs {
		r, err := http.Get(srv.URL + "/api/tasks/" + id)
		if err != nil {
			t.Errorf("GET task %d: %v", i, err)
			continue
		}
		var task domain.Task
		if err := json.NewDecoder(r.Body).Decode(&task); err != nil {
			r.Body.Close()
			t.Errorf("decode task %d: %v", i, err)
			continue
		}
		r.Body.Close()
		if task.Status != domain.StatusCompleted {
			t.Errorf("task %d (%s): expected COMPLETED, got %s", i, id, task.Status)
		}
	}
}
